#!/usr/bin/env python3
"""
Lit la base SQLite générée par JS_listener.py
et produit un rapport propre.

Usage:
    python3 sqlite_report.py --db /tmp/js_listener.sqlite3
    python3 sqlite_report.py --db /tmp/js_listener.sqlite3 -j
    python3 sqlite_report.py --db /tmp/js_listener.sqlite3 -o /tmp/report.json
"""

import argparse
import json
import sqlite3
import sys
from collections import defaultdict

def connect_db(path):
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn

def table_exists(conn, table_name):
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (table_name,)
    ).fetchone()
    return row is not None

def safe_fetchall(conn, query, params=()):
    try:
        return conn.execute(query, params).fetchall()
    except Exception as e:
        print(f"[DB-ERROR] {e}", file=sys.stderr)
        return []

def summarize_domain_resources(rows):
    domain_stats = defaultdict(lambda: {"count": 0, "urls": set()})
    for r in rows:
        domain = r["domain"] or "unknown"
        domain_stats[domain]["count"] += 1
        domain_stats[domain]["urls"].add(r["url"])
    return {
        domain: {
            "count": data["count"],
            "urls": sorted(data["urls"])
        }
        for domain, data in sorted(domain_stats.items())
    }

def summarize_domain_cookies(rows):
    domain_stats = defaultdict(lambda: {"count": 0, "names": defaultdict(int)})
    for r in rows:
        domain = r["domain"] or "unknown"
        domain_stats[domain]["count"] += 1
        name = r["name"] or "(empty)"
        domain_stats[domain]["names"][name] += 1
    return {
        domain: {
            "count": data["count"],
            "names": dict(sorted(data["names"].items()))
        }
        for domain, data in sorted(domain_stats.items())
    }

def generate_report(conn):
    if not table_exists(conn, "sessions"):
        return {
            "error": "Table 'sessions' not found. DB is probably empty or not generated by JS_listener.py."
        }

    sessions = safe_fetchall(conn, """
        SELECT *
        FROM sessions
        ORDER BY started_at DESC
    """)

    report = {
        "sessions": [],
        "total_sessions": len(sessions)
    }

    for session in sessions:
        sid = session["id"]

        resources = safe_fetchall(conn, """
            SELECT *
            FROM resources
            WHERE session_id = ?
            ORDER BY url, ts
        """, (sid,))

        network_events = safe_fetchall(conn, """
            SELECT *
            FROM network_events
            WHERE session_id = ?
            ORDER BY id
        """, (sid,))

        dependencies = safe_fetchall(conn, """
            SELECT *
            FROM dependencies
            WHERE session_id = ?
            ORDER BY id
        """, (sid,))

        mode_changes = safe_fetchall(conn, """
            SELECT *
            FROM mode_changes
            WHERE session_id = ?
            ORDER BY id
        """, (sid,))

        cookies = safe_fetchall(conn, """
            SELECT *
            FROM cookies
            WHERE session_id = ?
            ORDER BY domain, name, path
        """, (sid,))

        events = safe_fetchall(conn, """
            SELECT *
            FROM events
            WHERE session_id = ?
            ORDER BY id
        """, (sid,))

        session_report = {
            "id": sid,
            "target": session["target"],
            "started_at": session["started_at"],
            "ended_at": session["ended_at"],
            "status": session["status"],
            "user_agent": session["user_agent"],
            "headless": bool(session["headless"]),
            "resource_count": len(resources),
            "network_event_count": len(network_events),
            "cookie_count": len(cookies),
            "event_count": len(events),
            "domains": {
                "resources": summarize_domain_resources(resources),
                "cookies": summarize_domain_cookies(cookies)
            },
            "resources": [dict(r) for r in resources],
            "network_events": [dict(r) for r in network_events],
            "dependencies": [dict(r) for r in dependencies],
            "mode_changes": [dict(r) for r in mode_changes],
            "cookies": [dict(r) for r in cookies],
            "events": [dict(r) for r in events]
        }

        report["sessions"].append(session_report)

    return report

def print_text_report(report):
    print("=== JS Listener SQLite Report ===")
    print(f"Total sessions: {report.get('total_sessions', 0)}")

    if "error" in report:
        print(report["error"])
        return

    for s in report["sessions"]:
        print()
        print(f"Session: {s['id']}")
        print(f"  Target: {s['target']}")
        print(f"  Started: {s['started_at']}")
        print(f"  Ended: {s['ended_at']}")
        print(f"  Status: {s['status']}")
        print(f"  User-Agent: {s['user_agent']}")
        print(f"  Headless: {s['headless']}")
        print(f"  Resource count: {s['resource_count']}")
        print(f"  Network event count: {s['network_event_count']}")
        print(f"  Cookie count: {s['cookie_count']}")
        print(f"  Event count: {s['event_count']}")

        print("  Domains (resources):")
        if s["domains"]["resources"]:
            for domain, info in s["domains"]["resources"].items():
                print(f"    - {domain}: {info['count']} resources")
        else:
            print("    - none")

        print("  Domains (cookies):")
        if s["domains"]["cookies"]:
            for domain, info in s["domains"]["cookies"].items():
                print(f"    - {domain}: {info['count']} cookies")
        else:
            print("    - none")

def main():
    parser = argparse.ArgumentParser(description="Generate a readable report from the JS_listener SQLite DB.")
    parser.add_argument("--db", default="/tmp/js_listener.sqlite3", help="SQLite DB path")
    parser.add_argument("-o", "--output", help="Write report to JSON file")
    parser.add_argument("-j", "--json", action="store_true", help="Print JSON to stdout")
    args = parser.parse_args()

    conn = connect_db(args.db)
    report = generate_report(conn)
    conn.close()

    if "error" in report:
        print(report["error"], file=sys.stderr)
        sys.exit(1)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        print(f"[saved] {args.output}")

    if args.json or args.output:
        print(json.dumps(report, indent=2, ensure_ascii=False))

    if not args.json and not args.output:
        print_text_report(report)

if __name__ == "__main__":
    main()